_DB_NAME = "rais_anonymized"
##################################
#       FitBit Collection        #
##################################
_DB_FITBIT_COLLECTION_NAME = "fitbit"
_DB_FITBIT_COLLECTION_TYPE_KEY = "type"
_DB_FITBIT_COLLECTION_ID_KEY = "id"
_DB_FITBIT_COLLECTION_DATA_KEY = "data"

# --------------------------------#
#          Document types         #
# --------------------------------#
_DB_FITBIT_COLLECTION_DATA_TYPE_SLEEP_VALUE = "sleep"
_DB_FITBIT_COLLECTION_DATA_TYPE_COMP_TEMP_VALUE = "Computed Temperature"
_DB_FITBIT_COLLECTION_DATA_TYPE_DAILY_HRV_SUMMARY_VALUE = (
    "Daily Heart Rate Variability Summary"
)
_DB_FITBIT_COLLECTION_DATA_TYPE_DAILY_SPO2_VALUE = "Daily SpO2"
_DB_FITBIT_COLLECTION_DATA_TYPE_DEVICE_TEMP_VALUE = "Device Temperature"

# --------------------------------#
#         Sleep Documents         #
# --------------------------------#
_DB_FITBIT_COLLECTION_SLEEP_DATA_LOG_ID_KEY = "logId"
_DB_FITBIT_COLLECTION_SLEEP_DATA_DATE_OF_SLEEP_KEY = "dateOfSleep"
_DB_FITBIT_COLLECTION_SLEEP_DATA_START_TIME_KEY = "startTime"
_DB_FITBIT_COLLECTION_SLEEP_DATA_END_TIME_KEY = "endTime"
_DB_FITBIT_COLLECTION_SLEEP_DATA_DURATION_KEY = "duration"
_DB_FITBIT_COLLECTION_SLEEP_DATA_MIN_TO_FALL_ASLEEP_KEY = "minutesToFallAsleep"
_DB_FITBIT_COLLECTION_SLEEP_DATA_MIN_ASLEEP_KEY = "minutesAsleep"
_DB_FITBIT_COLLECTION_SLEEP_DATA_MIN_AWAKE_KEY = "minutesAwake"
_DB_FITBIT_COLLECTION_SLEEP_DATA_MIN_AFTER_WAKEUP_KEY = "minutesAfterWakeup"
_DB_FITBIT_COLLECTION_SLEEP_DATA_TIME_IN_BED_KEY = "timeInBed"
_DB_FITBIT_COLLECTION_SLEEP_DATA_EFFICIENCY_KEY = "efficiency"
_DB_FITBIT_COLLECTION_SLEEP_DATA_MAIN_SLEEP_KEY = "mainSleep"
_DB_FITBIT_COLLECTION_SLEEP_DATA_LEVELS_KEY = "levels"
_DB_FITBIT_COLLECTION_SLEEP_DATA_LEVELS_SUMMARY_KEY = "summary"
_DB_FITBIT_COLLECTION_SLEEP_DATA_LEVELS_SUMMARY_DEEP_KEY = "deep"
_DB_FITBIT_COLLECTION_SLEEP_DATA_LEVELS_SUMMARY_LIGHT_KEY = "light"
_DB_FITBIT_COLLECTION_SLEEP_DATA_LEVELS_SUMMARY_REM_KEY = "rem"
_DB_FITBIT_COLLECTION_SLEEP_DATA_LEVELS_SUMMARY_WAKE_KEY = "wake"
_DB_FITBIT_COLLECTION_SLEEP_DATA_LEVELS_DATA_KEY = "data"
_DB_FITBIT_COLLECTION_SLEEP_DATA_LEVELS_DATA_DATETIME_KEY = "dateTime"
_DB_FITBIT_COLLECTION_SLEEP_DATA_LEVELS_DATA_SECONDS_KEY = "seconds"
_DB_FITBIT_COLLECTION_SLEEP_DATA_LEVELS_DATA_LEVEL_KEY = "level"
_DB_FITBIT_COLLECTION_SLEEP_DATA_LEVELS_SHORT_DATA_KEY = "shortData"
_DB_FITBIT_COLLECTION_SLEEP_DATA_TYPE_KEY = "type"
_DB_FITBIT_COLLECTION_SLEEP_DATA_INFO_CODE_KEY = "infoCode"
_DB_FITBIT_COLLECTION_SLEEP_DATA_DEEP_COUNT_KEY = "deepCount"
_DB_FITBIT_COLLECTION_SLEEP_DATA_DEEP_MIN_KEY = "deepMinutes"
_DB_FITBIT_COLLECTION_SLEEP_DATA_DEEP_30_DAYS_AVG_MIN_KEY = "deepThirtydayavgminutes"
_DB_FITBIT_COLLECTION_SLEEP_DATA_WAKE_COUNT_KEY = "wakeCount"
_DB_FITBIT_COLLECTION_SLEEP_DATA_WAKE_MIN_KEY = "wakeMinutes"
_DB_FITBIT_COLLECTION_SLEEP_DATA_WAKE_30_DAYS_AVG_MIN_KEY = "wakeThirtydayavgminutes"
_DB_FITBIT_COLLECTION_SLEEP_DATA_LIGHT_COUNT_KEY = "lightCount"
_DB_FITBIT_COLLECTION_SLEEP_DATA_LIGHT_MIN_KEY = "lightMinutes"
_DB_FITBIT_COLLECTION_SLEEP_DATA_LIGHT_30_DAYS_AVG_MIN_KEY = "lightThirtydayavgminutes"
_DB_FITBIT_COLLECTION_SLEEP_DATA_REM_COUNT_KEY = "remCount"
_DB_FITBIT_COLLECTION_SLEEP_DATA_REM_MIN_KEY = "remMinutes"
_DB_FITBIT_COLLECTION_SLEEP_DATA_REM_30_DAYS_AVG_MIN_KEY = "remThirtydayavgminutes"
_DB_FITBIT_COLLECTION_SLEEP_DATA_RESTLESS_COUNT_KEY = "restlessCount"
_DB_FITBIT_COLLECTION_SLEEP_DATA_RESTLESS_MIN_KEY = "restlessMinutes"
_DB_FITBIT_COLLECTION_SLEEP_DATA_AWAKE_COUNT_KEY = "awakeCount"
_DB_FITBIT_COLLECTION_SLEEP_DATA_AWAKE_MIN_KEY = "awakeMinutes"
_DB_FITBIT_COLLECTION_SLEEP_DATA_ASLEEP_COUNT_KEY = "asleepCount"
_DB_FITBIT_COLLECTION_SLEEP_DATA_ASLEEP_MIN_KEY = "asleepMinutes"

# ---------------------------------------------#
#      Converted Temperature Documents         #
# ---------------------------------------------#
_DB_FITBIT_COLLECTION_COMP_TEMP_SLEEP_START_KEY = "sleep_start"
_DB_FITBIT_COLLECTION_COMP_TEMP_SLEEP_END_KEY = "sleep_end"
