_DB_NAME = "rais_anonymized"
##################################
#       FitBit Collection        #
##################################
_DB_FITBIT_COLLECTION_NAME = "fitbit"
_DB_FITBIT_COLLECTION_TYPE_KEY = "type"
_DB_FITBIT_COLLECTION_ID_KEY = "id"
_DB_FITBIT_COLLECTION_DATA_KEY = "data"

# --------------------------------#
#          Document types         #
# --------------------------------#
_DB_FITBIT_COLLECTION_DATA_TYPE_SLEEP_VALUE = "sleep"

# --------------------------------#
#         Sleep Documents         #
# --------------------------------#
_DB_FITBIT_COLLECTION_SLEEP_DATA_LOG_ID_KEY = "logId"
_DB_FITBIT_COLLECTION_SLEEP_DATE_OF_SLEEP_KEY = "dateOfSleep"
_DB_FITBIT_COLLECTION_SLEEP_DATA_START_TIME_KEY = "startTime"
_DB_FITBIT_COLLECTION_SLEEP_DATA_END_TIME_KEY = "endTime"
_DB_FITBIT_COLLECTION_SLEEP_DATA_DURATION_KEY = "duration"
_DB_FITBIT_COLLECTION_SLEEP_DATA_MIN_TO_FALL_ASLEEP_KEY = "minutesToFallAsleep"
_DB_FITBIT_COLLECTION_SLEEP_DATA_MIN_ASLEEP_KEY = "minutesAsleep"
_DB_FITBIT_COLLECTION_SLEEP_DATA_MIN_AWAKE_KEY = "minutesAwake"
_DB_FITBIT_COLLECTION_SLEEP_DATA_MIN_AFTER_WAKEUP_KEY = "minutesAfterWakeup"
_DB_FITBIT_COLLECTION_SLEEP_DATA_TIME_IN_BED_KEY = "timeInBed"
_DB_FITBIT_COLLECTION_SLEEP_DATA_EFFICIENCY_KEY = "efficiency"
_DB_FITBIT_COLLECTION_SLEEP_DATA_MAIN_SLEEP_KEY = "mainSleep"
_DB_FITBIT_COLLECTION_SLEEP_DATA_LEVELS_KEY = "levels"
_DB_FITBIT_COLLECTION_SLEEP_DATA_LEVELS_SUMMARY_KEY = "summary"
_DB_FITBIT_COLLECTION_SLEEP_DATA_LEVELS_SUMMARY_DEEP_KEY = "deep"
_DB_FITBIT_COLLECTION_SLEEP_DATA_LEVELS_SUMMARY_LIGHT_KEY = "light"
_DB_FITBIT_COLLECTION_SLEEP_DATA_LEVELS_SUMMARY_REM_KEY = "rem"
_DB_FITBIT_COLLECTION_SLEEP_DATA_LEVELS_SUMMARY_WAKE_KEY = "wake"
